# dist: trusty # KVM Setup

os:
  - linux
  - osx

language: go

go:
#  - 1.3
  - 1.4

env:
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_go_expensive
  - TEST_NO_FUSE=1 TEST_VERBOSE=1 TEST_SUITE=test_sharness_expensive

script:
  - make $TEST_SUITE

sudo: false #docker containers for CI
